// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "pei0804/goa-stater": Client
//
// Command:
// $ goagen
// --design=github.com/KokiKono/go_tutorial/design
// --out=$(GOPATH)/src/github.com/KokiKono/go_tutorial
// --version=v1.3.0

package client

import (
	"github.com/goadesign/goa"
	goaclient "github.com/goadesign/goa/client"
)

// Client is the pei0804/goa-stater service client.
type Client struct {
	*goaclient.Client
	AdminAuthSigner   goaclient.Signer
	GeneralAuthSigner goaclient.Signer
	Encoder           *goa.HTTPEncoder
	Decoder           *goa.HTTPDecoder
}

// New instantiates the client.
func New(c goaclient.Doer) *Client {
	client := &Client{
		Client:  goaclient.New(c),
		Encoder: goa.NewHTTPEncoder(),
		Decoder: goa.NewHTTPDecoder(),
	}

	// Setup encoders and decoders
	client.Encoder.Register(goa.NewJSONEncoder, "application/json")
	client.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	client.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	client.Decoder.Register(goa.NewJSONDecoder, "application/json")
	client.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	client.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	client.Encoder.Register(goa.NewJSONEncoder, "*/*")
	client.Decoder.Register(goa.NewJSONDecoder, "*/*")

	return client
}

// SetAdminAuthSigner sets the request signer for the adminAuth security scheme.
func (c *Client) SetAdminAuthSigner(signer goaclient.Signer) {
	c.AdminAuthSigner = signer
}

// SetGeneralAuthSigner sets the request signer for the generalAuth security scheme.
func (c *Client) SetGeneralAuthSigner(signer goaclient.Signer) {
	c.GeneralAuthSigner = signer
}
